
INSERT INTO perfil values (1, "COORDENADOR_EXTENSAO");
INSERT INTO perfil values (2, "COORDENADOR_PESQUISA");
INSERT INTO perfil values (3, "COORDENADOR_INOVACAO");
INSERT INTO perfil values (4, "ADMINSTRADOR");