version: '3.8'

services:
  mariadb:
    image: mariadb:10.10
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mariadb_network
    env_file:
      - .env

volumes:
  mariadb_data:

networks:
  mariadb_network:
    driver: bridge
